# Generated by Django 4.0.5 on 2022-06-13 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country_flag', models.CharField(blank=True, max_length=200, null=True)),
                ('event_media', models.FileField(blank=True, null=True, upload_to='event_media/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='event_media/thumbnail/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('upcoming', 'upcoming'), ('live', 'live'), ('finished', 'finished')], default='upcoming', max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportevents.category')),
            ],
        ),
    ]
