# Generated by Django 4.0.5 on 2022-06-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportevents', '0002_sportevent_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportevent',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='sportevent',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
