# Generated by Django 4.0.5 on 2022-07-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportevents', '0003_alter_sportevent_options_sportevent_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportevent',
            name='isSport',
            field=models.BooleanField(default=True),
        ),
    ]
